for index in range(2):
    maqueen.motor_run(maqueen.Motors.ALL, maqueen.Dir.CW, 255)
    basic.pause(1000)
    maqueen.motor_stop(maqueen.Motors.ALL)
    basic.pause(500)
    maqueen.motor_run(maqueen.Motors.ALL, maqueen.Dir.CCW, 255)
    basic.pause(1000)
    maqueen.motor_stop(maqueen.Motors.ALL)
basic.pause(10000)
maqueen.motor_run(maqueen.Motors.M2, maqueen.Dir.CW, 200)
basic.pause(2000)
maqueen.motor_run(maqueen.Motors.ALL, maqueen.Dir.CW, 255)
basic.pause(10000)